SELECT
  EMPLOYEES.EMPLOYEE_ID,
  EMPLOYEES.FIRST_NAME,
  EMPLOYEES.DEPARTMENT_ID,
  DEPARTMENTS.DEPARTMENT_NAME
FROM EMPLOYEES,
  DEPARTMENTS
WHERE EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_NAME
ORDER BY EMPLOYEE_ID;

SELECT
  EMPLOYEES.EMPLOYEE_ID,
  EMPLOYEES.FIRST_NAME,
  EMPLOYEES.DEPARTMENT_ID,
  DEPARTMENTS.DEPARTMENT_NAME
FROM EMPLOYEES,
  DEPARTMENTS
WHERE EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
  AND EMPLOYEES.DEPARTMENT_ID > 40
ORDER BY EMPLOYEE_ID;

--using table alias
SELECT
  emp.EMPLOYEE_ID,
  EMP.FIRST_NAME,
  EMP.DEPARTMENT_ID,
  dept.DEPARTMENT_NAME
FROM EMPLOYEES EMP,
  DEPARTMENTS DEPT
WHERE emp.DEPARTMENT_ID = dept.DEPARTMENT_ID
ORDER BY EMPLOYEE_ID;

--join more than 2 tables
SELECT
  EMP.EMPLOYEE_ID,
  EMP.FIRST_NAME,
  emp.DEPARTMENT_ID,
  DEPT.DEPARTMENT_NAME,
  DEPT.location_id,
  loc.city
FROM
  EMPLOYEES EMP,
  DEPARTMENTS DEPT,
  locations loc
WHERE EMP.DEPARTMENT_ID = DEPT.DEPARTMENT_ID
  AND DEPT.location_id = loc.location_id
ORDER BY EMPLOYEE_ID;  
